import { IFields } from '../interfaces'

export type TDialects = 'mysql' | 'postgres'

export type TRuleHandler = string | void | Promise<string | void> | Promise<string | IFields | void>

export type TRuleNames =
  | 'allowEmpty'
  | 'allowFalse'
  | 'allowNull'
  | 'allowZero'
  | 'ifExists'
  | 'find'
  | 'findRaw'
  | 'unique'
  | 'as'
  | 'between'
  | 'if'
  | 'length'
  | 'max'
  | 'min'
  | 'only'
  | 'required'
  | 'validate'
  | 'date'
  | 'email'
  | 'tel'
  | 'array'
  | 'boolean'
  | 'number'
  | 'object'
  | 'string'
